-- ════════════════════════════════════════════════════════════════════════════
-- PROD-PARITY RECONCILIATION (§9.2 cutover prerequisite)
--
-- Creates the 18 tables (+ 7 enums + the users.is_bot column) that the live prod
-- DB (cosmos @ 127.0.0.1:5432) has but v2 was missing — so the per-tenant cutover
-- copies prod rows into a structurally-identical v2 schema (parity-gate clean:
-- `prisma migrate diff --from <restored-prod> --to schema.prisma` is EMPTY).
--
-- SHAPE matches prod EXACTLY (column types/nullability/defaults/@map/indexes/FKs,
-- incl. chat_bot_runs.triggered_by ON DELETE RESTRICT). Generated by diffing the
-- pre-parity v2 migration state against the new schema datamodel, then hand-
-- trimmed to ONLY the additive parity statements (the raw diff also emitted
-- destructive noise for v2's generated/Unsupported columns — content_tsv, the
-- pgvector embedding indexes, the audit hash-chain seq/head — which are v2-native
-- and must NOT be touched here; see AGENTS.md "content_tsv → never reset").
--
-- Hand-written (no `prisma migrate dev`); applied via `migrate deploy` as the
-- OWNER (cosmos). FULLY WIRED in v2: chat_bots (12 prod rows) + work_item_links
-- (42 prod rows). The rest are SCHEMA-ONLY (empty in prod; ports the shape so
-- data migrates + parity holds — UI/routes deferred to roadmap).
-- ════════════════════════════════════════════════════════════════════════════

-- CreateEnum
CREATE TYPE "LinkType" AS ENUM ('BLOCKS', 'BLOCKED_BY', 'RELATES', 'DUPLICATES', 'PREDECESSOR', 'SUCCESSOR', 'CLONES');

-- CreateEnum
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'SENT', 'PARTIAL', 'PAID', 'VOID');

-- CreateEnum
CREATE TYPE "EmploymentType" AS ENUM ('SALARY', 'HOURLY');

-- CreateEnum
CREATE TYPE "PayRunStatus" AS ENUM ('DRAFT', 'POSTED');

-- CreateEnum
CREATE TYPE "ChatBotToolScope" AS ENUM ('NONE', 'READONLY', 'FULL');

-- CreateEnum
CREATE TYPE "BankAccountProvider" AS ENUM ('MANUAL_IMPORT', 'AKOYA');

-- CreateEnum
CREATE TYPE "BankTxnStatus" AS ENUM ('IMPORTED', 'CATEGORIZED', 'MATCHED', 'POSTED', 'EXCLUDED');


-- AlterTable: synthetic AI-bot accounts (chat bots). Additive, default false.
-- Required for the chat_bots feature (bot messages authored by the bot user) and
-- for the cutover to round-trip prod's 12 bot users with their flag intact.
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "is_bot" BOOLEAN NOT NULL DEFAULT false;

-- CreateTable
CREATE TABLE "org_ai_settings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "provider" TEXT NOT NULL DEFAULT 'anthropic',
    "model" TEXT,
    "anthropic_api_key" JSONB,
    "claude_oauth_token" JSONB,
    "openai_api_key" JSONB,
    "oauth_access_token" JSONB,
    "oauth_refresh_token" JSONB,
    "oauth_expires_at" TIMESTAMP(3),
    "updated_by_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "org_ai_settings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_item_links" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "source_item_id" UUID NOT NULL,
    "target_item_id" UUID NOT NULL,
    "type" "LinkType" NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "work_item_links_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "work_item_attachments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "work_item_id" UUID NOT NULL,
    "file_name" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "mime_type" TEXT,
    "size_bytes" INTEGER,
    "external_ref" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "work_item_attachments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invoices" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "number" TEXT NOT NULL,
    "contact_id" UUID,
    "contract_id" UUID,
    "bill_to_name" TEXT NOT NULL,
    "bill_to_email" TEXT,
    "status" "InvoiceStatus" NOT NULL DEFAULT 'DRAFT',
    "issue_date" DATE,
    "due_date" DATE,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "subtotal" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "tax_total" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "total" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "amount_paid" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "terms" TEXT,
    "notes" TEXT,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "invoices_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "invoice_line_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "invoice_id" UUID NOT NULL,
    "description" TEXT NOT NULL,
    "quantity" DECIMAL(19,4) NOT NULL DEFAULT 1,
    "unit_price" DECIMAL(19,4) NOT NULL,
    "tax_rate" DECIMAL(9,6) NOT NULL DEFAULT 0,
    "amount" DECIMAL(19,4) NOT NULL,
    "product_id" UUID,
    "sort_order" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "invoice_line_items_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "payments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "invoice_id" UUID NOT NULL,
    "amount" DECIMAL(19,4) NOT NULL,
    "method" TEXT NOT NULL DEFAULT 'other',
    "reference" TEXT,
    "received_at" DATE NOT NULL,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "payments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "employees" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "employment_type" "EmploymentType" NOT NULL DEFAULT 'HOURLY',
    "cost_rate" DECIMAL(19,4) NOT NULL,
    "labor_category" TEXT,
    "classification" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "start_date" DATE,
    "end_date" DATE,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "employees_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "pay_runs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "label" TEXT NOT NULL DEFAULT '',
    "period_start" DATE NOT NULL,
    "period_end" DATE NOT NULL,
    "status" "PayRunStatus" NOT NULL DEFAULT 'DRAFT',
    "labor_cost" DECIMAL(19,4) NOT NULL DEFAULT 0,
    "posted_at" TIMESTAMP(3),
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "pay_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tax_rates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "rate" DECIMAL(9,6) NOT NULL,
    "jurisdiction" TEXT,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tax_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "documents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "project_id" UUID NOT NULL,
    "title" TEXT NOT NULL,
    "classification_level" "ClassificationLevel" NOT NULL DEFAULT 'UNCLASSIFIED',
    "storage_key" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "content_type" TEXT NOT NULL,
    "size" INTEGER NOT NULL,
    "uploaded_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_thread_followers" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "channel_id" UUID NOT NULL,
    "parent_message_id" UUID NOT NULL,
    "last_read_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_thread_followers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_alert_keywords" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "keyword" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_alert_keywords_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_bots" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "key" TEXT NOT NULL,
    "display_name" TEXT NOT NULL,
    "persona" TEXT NOT NULL DEFAULT '',
    "model" TEXT NOT NULL DEFAULT 'sonnet',
    "tool_scope" "ChatBotToolScope" NOT NULL DEFAULT 'NONE',
    "enabled_mcp" BOOLEAN NOT NULL DEFAULT false,
    "schedule_cron" TEXT,
    "user_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "chat_bots_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_bot_channels" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "bot_id" UUID NOT NULL,
    "channel_id" UUID NOT NULL,
    "auto_respond" BOOLEAN NOT NULL DEFAULT false,
    "enabled" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_bot_channels_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "chat_bot_runs" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "bot_id" UUID NOT NULL,
    "message_id" UUID NOT NULL,
    "triggered_by_user_id" UUID NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "chat_bot_runs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bank_accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "institution" TEXT,
    "mask" TEXT,
    "currency" TEXT NOT NULL DEFAULT 'USD',
    "provider" "BankAccountProvider" NOT NULL DEFAULT 'MANUAL_IMPORT',
    "ledger_account_id" UUID,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bank_accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bank_transactions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "bank_account_id" UUID NOT NULL,
    "external_id" TEXT,
    "fingerprint" TEXT NOT NULL,
    "posted_date" DATE NOT NULL,
    "amount" DECIMAL(19,4) NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "pending" BOOLEAN NOT NULL DEFAULT false,
    "status" "BankTxnStatus" NOT NULL DEFAULT 'IMPORTED',
    "matched_expense_id" UUID,
    "matched_revenue_id" UUID,
    "category" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "bank_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "bank_rules" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "org_id" UUID NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "description_contains" TEXT,
    "direction" TEXT NOT NULL DEFAULT 'any',
    "amount_min" DECIMAL(19,4),
    "amount_max" DECIMAL(19,4),
    "category" TEXT NOT NULL,
    "priority" INTEGER NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "created_by_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "bank_rules_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "org_ai_settings_org_id_key" ON "org_ai_settings"("org_id");

-- CreateIndex
CREATE INDEX "work_item_links_org_id_source_item_id_idx" ON "work_item_links"("org_id", "source_item_id");

-- CreateIndex
CREATE INDEX "work_item_attachments_org_id_work_item_id_idx" ON "work_item_attachments"("org_id", "work_item_id");

-- CreateIndex
CREATE INDEX "invoices_org_id_status_idx" ON "invoices"("org_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "invoices_org_id_number_key" ON "invoices"("org_id", "number");

-- CreateIndex
CREATE INDEX "invoice_line_items_invoice_id_idx" ON "invoice_line_items"("invoice_id");

-- CreateIndex
CREATE INDEX "payments_org_id_invoice_id_idx" ON "payments"("org_id", "invoice_id");

-- CreateIndex
CREATE INDEX "employees_org_id_status_idx" ON "employees"("org_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "employees_org_id_user_id_key" ON "employees"("org_id", "user_id");

-- CreateIndex
CREATE INDEX "pay_runs_org_id_status_idx" ON "pay_runs"("org_id", "status");

-- CreateIndex
CREATE INDEX "tax_rates_org_id_is_active_idx" ON "tax_rates"("org_id", "is_active");

-- CreateIndex
CREATE INDEX "documents_org_id_project_id_idx" ON "documents"("org_id", "project_id");

-- CreateIndex
CREATE INDEX "chat_thread_followers_user_id_idx" ON "chat_thread_followers"("user_id");

-- CreateIndex
CREATE INDEX "chat_thread_followers_parent_message_id_idx" ON "chat_thread_followers"("parent_message_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_thread_followers_user_id_parent_message_id_key" ON "chat_thread_followers"("user_id", "parent_message_id");

-- CreateIndex
CREATE INDEX "chat_alert_keywords_user_id_idx" ON "chat_alert_keywords"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_alert_keywords_user_id_keyword_key" ON "chat_alert_keywords"("user_id", "keyword");

-- CreateIndex
CREATE UNIQUE INDEX "chat_bots_user_id_key" ON "chat_bots"("user_id");

-- CreateIndex
CREATE INDEX "chat_bots_org_id_idx" ON "chat_bots"("org_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_bots_org_id_key_key" ON "chat_bots"("org_id", "key");

-- CreateIndex
CREATE INDEX "chat_bot_channels_channel_id_idx" ON "chat_bot_channels"("channel_id");

-- CreateIndex
CREATE UNIQUE INDEX "chat_bot_channels_bot_id_channel_id_key" ON "chat_bot_channels"("bot_id", "channel_id");

-- CreateIndex
CREATE INDEX "chat_bot_runs_bot_id_created_at_idx" ON "chat_bot_runs"("bot_id", "created_at");

-- CreateIndex
CREATE INDEX "chat_bot_runs_message_id_idx" ON "chat_bot_runs"("message_id");

-- CreateIndex
CREATE INDEX "bank_accounts_org_id_idx" ON "bank_accounts"("org_id");

-- CreateIndex
CREATE INDEX "bank_transactions_org_id_bank_account_id_status_idx" ON "bank_transactions"("org_id", "bank_account_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "bank_transactions_bank_account_id_external_id_key" ON "bank_transactions"("bank_account_id", "external_id");

-- CreateIndex
CREATE UNIQUE INDEX "bank_transactions_bank_account_id_fingerprint_key" ON "bank_transactions"("bank_account_id", "fingerprint");

-- CreateIndex
CREATE INDEX "bank_rules_org_id_is_active_priority_idx" ON "bank_rules"("org_id", "is_active", "priority");
-- AddForeignKey
ALTER TABLE "org_ai_settings" ADD CONSTRAINT "org_ai_settings_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_item_links" ADD CONSTRAINT "work_item_links_source_item_id_fkey" FOREIGN KEY ("source_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_item_links" ADD CONSTRAINT "work_item_links_target_item_id_fkey" FOREIGN KEY ("target_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "work_item_attachments" ADD CONSTRAINT "work_item_attachments_work_item_id_fkey" FOREIGN KEY ("work_item_id") REFERENCES "work_items"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "invoice_line_items" ADD CONSTRAINT "invoice_line_items_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "payments" ADD CONSTRAINT "payments_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_project_id_fkey" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_thread_followers" ADD CONSTRAINT "chat_thread_followers_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_thread_followers" ADD CONSTRAINT "chat_thread_followers_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "chat_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_thread_followers" ADD CONSTRAINT "chat_thread_followers_parent_message_id_fkey" FOREIGN KEY ("parent_message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_alert_keywords" ADD CONSTRAINT "chat_alert_keywords_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bots" ADD CONSTRAINT "chat_bots_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bots" ADD CONSTRAINT "chat_bots_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bot_channels" ADD CONSTRAINT "chat_bot_channels_bot_id_fkey" FOREIGN KEY ("bot_id") REFERENCES "chat_bots"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bot_channels" ADD CONSTRAINT "chat_bot_channels_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "chat_channels"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bot_runs" ADD CONSTRAINT "chat_bot_runs_bot_id_fkey" FOREIGN KEY ("bot_id") REFERENCES "chat_bots"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bot_runs" ADD CONSTRAINT "chat_bot_runs_message_id_fkey" FOREIGN KEY ("message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "chat_bot_runs" ADD CONSTRAINT "chat_bot_runs_triggered_by_user_id_fkey" FOREIGN KEY ("triggered_by_user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "bank_transactions" ADD CONSTRAINT "bank_transactions_bank_account_id_fkey" FOREIGN KEY ("bank_account_id") REFERENCES "bank_accounts"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ────────────────────────────────────────────────────────────────────────────
-- Least-privilege DML grant for the app role (cosmos_app).
--
-- The 20260606050000_audit_immutability migration set `ALTER DEFAULT PRIVILEGES
-- FOR ROLE cosmos ... GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO cosmos_app`,
-- so tables created here (as cosmos) AUTO-grant DML to cosmos_app. We GRANT
-- explicitly too (belt-and-suspenders) so a DB whose default-privileges weren't
-- in effect at create time still gets the app role wired. None of these 18 are
-- audit/immutable tables — they get full DML (unlike audit_logs/egress_decisions
-- which are append-only). Guarded so a DB without the cosmos_app role (e.g. a
-- throwaway parity scratch) is a clean no-op.
-- ────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'cosmos_app') THEN
    GRANT SELECT, INSERT, UPDATE, DELETE ON
      "org_ai_settings", "work_item_links", "work_item_attachments",
      "invoices", "invoice_line_items", "payments",
      "employees", "pay_runs", "tax_rates", "documents",
      "chat_thread_followers", "chat_alert_keywords",
      "chat_bots", "chat_bot_channels", "chat_bot_runs",
      "bank_accounts", "bank_transactions", "bank_rules"
    TO cosmos_app;
  END IF;
END $$;
