/**
 * NIST SP 800-171 Rev. 2 control baseline (all 110 security requirements across
 * the 14 families). This is the catalog COSMOS provisions for regulated (GOV)
 * organizations so a CMMC Level 2 / 800-171 assessment is available
 * out-of-the-box. CMMC L2 maps 1:1 to these 110 requirements.
 *
 * Source of truth for `provisionComplianceBaseline` and the demo seed.
 */
export interface BaselineControl {
  /** 800-171 requirement number, e.g. "3.1.1". */
  controlId: string;
  title: string;
  /** Family label, e.g. "Access Control". */
  family: string;
}

export const NIST_800_171_FAMILIES: Record<string, string> = {
  "3.1": "Access Control",
  "3.2": "Awareness and Training",
  "3.3": "Audit and Accountability",
  "3.4": "Configuration Management",
  "3.5": "Identification and Authentication",
  "3.6": "Incident Response",
  "3.7": "Maintenance",
  "3.8": "Media Protection",
  "3.9": "Personnel Security",
  "3.10": "Physical Protection",
  "3.11": "Risk Assessment",
  "3.12": "Security Assessment",
  "3.13": "System and Communications Protection",
  "3.14": "System and Information Integrity",
};

function familyOf(controlId: string): string {
  const parts = controlId.split(".");
  return NIST_800_171_FAMILIES[`${parts[0]}.${parts[1]}`] ?? "Other";
}

const RAW: Array<[string, string]> = [
  ["3.1.1", "Limit system access to authorized users and devices"],
  ["3.1.2", "Limit access to permitted transactions and functions"],
  ["3.1.3", "Control the flow of CUI in accordance with approved authorizations"],
  ["3.1.4", "Separate the duties of individuals to reduce risk"],
  ["3.1.5", "Employ the principle of least privilege"],
  ["3.1.6", "Use non-privileged accounts for non-security functions"],
  ["3.1.7", "Prevent non-privileged users from executing privileged functions"],
  ["3.1.8", "Limit unsuccessful logon attempts"],
  ["3.1.9", "Provide privacy and security notices consistent with CUI rules"],
  ["3.1.10", "Use session lock with pattern-hiding displays"],
  ["3.1.11", "Terminate user sessions after a defined condition"],
  ["3.1.12", "Monitor and control remote access sessions"],
  ["3.1.13", "Employ cryptographic mechanisms to protect remote access"],
  ["3.1.14", "Route remote access via managed access control points"],
  ["3.1.15", "Authorize remote execution of privileged commands"],
  ["3.1.16", "Authorize wireless access prior to allowing connections"],
  ["3.1.17", "Protect wireless access using authentication and encryption"],
  ["3.1.18", "Control connection of mobile devices"],
  ["3.1.19", "Encrypt CUI on mobile devices and platforms"],
  ["3.1.20", "Verify and control connections to external systems"],
  ["3.1.21", "Limit use of portable storage devices on external systems"],
  ["3.1.22", "Control CUI posted or processed on publicly accessible systems"],
  ["3.2.1", "Ensure personnel are trained on security risks and policies"],
  ["3.2.2", "Train personnel to carry out their security duties"],
  ["3.2.3", "Provide security awareness training on insider threat"],
  ["3.3.1", "Create and retain system audit logs and records"],
  ["3.3.2", "Ensure actions are traceable to individual users"],
  ["3.3.3", "Review and update logged events"],
  ["3.3.4", "Alert on audit logging process failures"],
  ["3.3.5", "Correlate audit review, analysis, and reporting"],
  ["3.3.6", "Provide audit record reduction and report generation"],
  ["3.3.7", "Synchronize system clocks to an authoritative source"],
  ["3.3.8", "Protect audit information and tools from unauthorized access"],
  ["3.3.9", "Limit management of audit logging to a privileged subset"],
  ["3.4.1", "Establish and maintain baseline configurations and inventories"],
  ["3.4.2", "Establish and enforce security configuration settings"],
  ["3.4.3", "Track, review, approve, and log configuration changes"],
  ["3.4.4", "Analyze the security impact of changes prior to implementation"],
  ["3.4.5", "Define, document, and enforce access restrictions for changes"],
  ["3.4.6", "Employ the principle of least functionality"],
  ["3.4.7", "Restrict nonessential programs, ports, protocols, and services"],
  ["3.4.8", "Apply deny-by-exception (blacklist/whitelist) for software"],
  ["3.4.9", "Control and monitor user-installed software"],
  ["3.5.1", "Identify system users, processes, and devices"],
  ["3.5.2", "Authenticate identities before granting access"],
  ["3.5.3", "Use multifactor authentication for access"],
  ["3.5.4", "Employ replay-resistant authentication mechanisms"],
  ["3.5.5", "Prevent reuse of identifiers for a defined period"],
  ["3.5.6", "Disable identifiers after a period of inactivity"],
  ["3.5.7", "Enforce a minimum password complexity"],
  ["3.5.8", "Prohibit password reuse for a number of generations"],
  ["3.5.9", "Allow temporary password use with immediate change"],
  ["3.5.10", "Store and transmit only cryptographically-protected passwords"],
  ["3.5.11", "Obscure feedback of authentication information"],
  ["3.6.1", "Establish an operational incident-handling capability"],
  ["3.6.2", "Track, document, and report incidents to officials"],
  ["3.6.3", "Test the organizational incident response capability"],
  ["3.7.1", "Perform maintenance on organizational systems"],
  ["3.7.2", "Provide controls on tools, techniques, and personnel for maintenance"],
  ["3.7.3", "Sanitize equipment removed for off-site maintenance"],
  ["3.7.4", "Check media containing diagnostic programs for malicious code"],
  ["3.7.5", "Require MFA to establish nonlocal maintenance sessions"],
  ["3.7.6", "Supervise maintenance activities of personnel without access"],
  ["3.8.1", "Protect system media containing CUI"],
  ["3.8.2", "Limit access to CUI on system media to authorized users"],
  ["3.8.3", "Sanitize or destroy system media before disposal or reuse"],
  ["3.8.4", "Mark media with necessary CUI markings and distribution limits"],
  ["3.8.5", "Control access to media and maintain accountability during transport"],
  ["3.8.6", "Implement cryptographic protection of CUI on media in transport"],
  ["3.8.7", "Control the use of removable media on system components"],
  ["3.8.8", "Prohibit use of portable storage with no identifiable owner"],
  ["3.8.9", "Protect the confidentiality of backup CUI at storage locations"],
  ["3.9.1", "Screen individuals prior to authorizing access to CUI"],
  ["3.9.2", "Protect CUI during personnel actions (termination/transfer)"],
  ["3.10.1", "Limit physical access to systems and equipment"],
  ["3.10.2", "Protect and monitor the physical facility and infrastructure"],
  ["3.10.3", "Escort visitors and monitor visitor activity"],
  ["3.10.4", "Maintain audit logs of physical access"],
  ["3.10.5", "Control and manage physical access devices"],
  ["3.10.6", "Enforce safeguarding measures for CUI at alternate work sites"],
  ["3.11.1", "Periodically assess risk to operations and assets"],
  ["3.11.2", "Scan for vulnerabilities and remediate in a timely manner"],
  ["3.11.3", "Remediate vulnerabilities in accordance with risk assessments"],
  ["3.12.1", "Periodically assess the security controls for effectiveness"],
  ["3.12.2", "Develop and implement plans of action (POA&M)"],
  ["3.12.3", "Monitor security controls on an ongoing basis"],
  ["3.12.4", "Develop, document, and update System Security Plans"],
  ["3.13.1", "Monitor and control communications at system boundaries"],
  ["3.13.2", "Employ architectural designs promoting effective security"],
  ["3.13.3", "Separate user functionality from system management functionality"],
  ["3.13.4", "Prevent unauthorized information transfer via shared resources"],
  ["3.13.5", "Implement subnetworks for publicly accessible components"],
  ["3.13.6", "Deny network traffic by default and allow by exception"],
  ["3.13.7", "Prevent remote devices from split tunneling"],
  ["3.13.8", "Use cryptography to protect CUI during transmission"],
  ["3.13.9", "Terminate network connections at the end of sessions"],
  ["3.13.10", "Establish and manage cryptographic keys"],
  ["3.13.11", "Employ FIPS-validated cryptography to protect CUI"],
  ["3.13.12", "Prohibit remote activation of collaborative computing devices"],
  ["3.13.13", "Control and monitor use of mobile code"],
  ["3.13.14", "Control and monitor use of VoIP technologies"],
  ["3.13.15", "Protect the authenticity of communications sessions"],
  ["3.13.16", "Protect the confidentiality of CUI at rest"],
  ["3.14.1", "Identify, report, and correct system flaws in a timely manner"],
  ["3.14.2", "Provide protection from malicious code"],
  ["3.14.3", "Monitor security alerts and advisories and take action"],
  ["3.14.4", "Update malicious code protection mechanisms"],
  ["3.14.5", "Perform periodic and real-time scans of the system"],
  ["3.14.6", "Monitor systems including inbound/outbound traffic"],
  ["3.14.7", "Identify unauthorized use of organizational systems"],
];

export const NIST_800_171_CONTROLS: BaselineControl[] = RAW.map(([controlId, title]) => ({
  controlId,
  title,
  family: familyOf(controlId),
}));
