apiVersion: ENC[AES256_GCM,data:C8s=,iv:zVgnQ7tol6irnXJ+voDRJTOT3TFE8lzA2YVF9WrufWk=,tag:inFFru79SK4eHXOirCPRqg==,type:str]
kind: ENC[AES256_GCM,data:RnokmPK9,iv:EzvVIO5xTEs21P7hxd7wamxUoU8wJub74lvHWcRNBq0=,tag:f3xF+H7Ag/shsR6e2y+Vnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JtlGy+8ZLv5w8ln+2L7U0hWh,iv:vMoDZu9ZZ/PU1+rsTIf5gAT2+ZEBmo8o2HDnGQhqT8A=,tag:sDwVOg1HM13JkMGEfBBZXQ==,type:str]
    namespace: ENC[AES256_GCM,data:nBw+s7OM,iv:G7jORkMmep8m1wO1QrBkMOeek7bWIWXUO6W/wjXKQu4=,tag:8MrEKZ0J2M/rNN83h08a4g==,type:str]
type: ENC[AES256_GCM,data:kGa7gFO5,iv:+0/nMmHQvsMFDC5Sty1js71cDP8sKUBf+UuJsfcM3l4=,tag:zPOQVXW1ID40sk+cMDkXKA==,type:str]
stringData:
    SSO_VAULT_KEY: ENC[AES256_GCM,data:aMquoHKZwFzAFbKdT3RQvH7naycqcnJJy6sUiIwRRs4T48oEfQuxUJu++18=,iv:eMPVWaZyJJ2R9pLo4eR2OSP9erwyKs845SXW2GCHipc=,tag:p7igQvO6yZ3ZiZnQI9uaWQ==,type:str]
    WORM_MANIFEST_HMAC_KEY: ENC[AES256_GCM,data:eRHAgGBCAzAurp4ueI14D7PI5MfrAT49N+jYlgiboGdOB5CvU0tUPhjrjIonXkbfScnhImK/1BqZM0KRSVfwgA==,iv:bvZmRK+EAWwPaYbhP1ld2OF3dwqtPfMJjpedRGHpfXw=,tag:mZVe31+D5ga7iXnsMAImdg==,type:str]
    INTERNAL_ADMINS: ENC[AES256_GCM,data:Vz6ohVK8OSNuuar3PqgMLeyfhHL//12kysJvpQ==,iv:huTJLgwu/vjgKCrvw1s2F0ShgsD4o/y5ri5KVaOF0Cs=,tag:CQsHM75TvJJz8Bpy0c0KaA==,type:str]
    COSMOS_APP_PASSWORD: ENC[AES256_GCM,data:PxAP3lMUKGKt+s3AFtXgRwfoM+wvqPt1B45T4GH+CD+24D4s7q73DHpOGDnzgWx7,iv:tL4wE6qrfKoj4GXN5oTVm55KEjURslilxIJIE7L1r/0=,tag:lZ0DGxDDzge1dzj/35ZO1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MXQ1d1o1dWtBdHFYaWhu
            TXY3cWJOY1h2Ulg1M2pQRlEzSzg2ZFpnN1YwClM2VFpFeHNUNnFwZjZCMG15M0Fz
            L3MvQ0l4aEtubytJa2JrWkw3MCs0Y1EKLS0tIHBLUGVia2x3NWU4L2syWFBVNjhH
            eEwvRlZUZlFlUzJSOUpuZWhjczZQRkkKLhZhLVldmWgZ84awLuFaQVX7JbqApZkI
            aQoe1W+kXs3PRbOMiGHm/j6Ves3Jca9MEn4l7JV9jF4iU2GEGMDHgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132pptnhr58gmqe965wpwxv3p2ud0q95up586fn0wvdh5zljvn48sdq0k6j
    lastmodified: "2026-06-30T00:11:57Z"
    mac: ENC[AES256_GCM,data:NRgrFeySpX5x5AaN5AUJBzf2cQx3Q+1QIMrpotfvMzXV1UUwYK02D2H1YOs8lNd6hDHB/1fXHHhDpv9xKtWVE9Fsi9ihSDnk6b2j+VhW7Em9x/vqjPZTQn82RnqJQTC9b/ur0tSo9WYK9imJ+2vgz33mvSz3PyBY590qkDiGAA0=,iv:a9IipZIe2ilyiTLXAm9epca7uOGofe1s0gunz8WJSwA=,tag:PY3zSzhCNNXfWOnl1VP73w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
