apiVersion: ENC[AES256_GCM,data:C8s=,iv:zVgnQ7tol6irnXJ+voDRJTOT3TFE8lzA2YVF9WrufWk=,tag:inFFru79SK4eHXOirCPRqg==,type:str]
kind: ENC[AES256_GCM,data:RnokmPK9,iv:EzvVIO5xTEs21P7hxd7wamxUoU8wJub74lvHWcRNBq0=,tag:f3xF+H7Ag/shsR6e2y+Vnw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JtlGy+8ZLv5w8ln+2L7U0hWh,iv:vMoDZu9ZZ/PU1+rsTIf5gAT2+ZEBmo8o2HDnGQhqT8A=,tag:sDwVOg1HM13JkMGEfBBZXQ==,type:str]
    namespace: ENC[AES256_GCM,data:nBw+s7OM,iv:G7jORkMmep8m1wO1QrBkMOeek7bWIWXUO6W/wjXKQu4=,tag:8MrEKZ0J2M/rNN83h08a4g==,type:str]
type: ENC[AES256_GCM,data:kGa7gFO5,iv:+0/nMmHQvsMFDC5Sty1js71cDP8sKUBf+UuJsfcM3l4=,tag:zPOQVXW1ID40sk+cMDkXKA==,type:str]
stringData:
    SSO_VAULT_KEY: ENC[AES256_GCM,data:IAoi6+hHD9s2TZz63F193A6cpsV+KtnthZJnnGhODE+GW9T5HcIzEugxlRoz0TE9MHLSUrhykVULxSKgxrk0kg==,iv:eCh6xeyxEfOk5WtW1Wc2fpmcyjBdffRIaFf53vk7NTM=,tag:OJ1DhsadXF2jv/6fMObNZA==,type:str]
    WORM_MANIFEST_HMAC_KEY: ENC[AES256_GCM,data:eRHAgGBCAzAurp4ueI14D7PI5MfrAT49N+jYlgiboGdOB5CvU0tUPhjrjIonXkbfScnhImK/1BqZM0KRSVfwgA==,iv:bvZmRK+EAWwPaYbhP1ld2OF3dwqtPfMJjpedRGHpfXw=,tag:mZVe31+D5ga7iXnsMAImdg==,type:str]
    INTERNAL_ADMINS: ENC[AES256_GCM,data:Vz6ohVK8OSNuuar3PqgMLeyfhHL//12kysJvpQ==,iv:huTJLgwu/vjgKCrvw1s2F0ShgsD4o/y5ri5KVaOF0Cs=,tag:CQsHM75TvJJz8Bpy0c0KaA==,type:str]
    COSMOS_APP_PASSWORD: ENC[AES256_GCM,data:PxAP3lMUKGKt+s3AFtXgRwfoM+wvqPt1B45T4GH+CD+24D4s7q73DHpOGDnzgWx7,iv:tL4wE6qrfKoj4GXN5oTVm55KEjURslilxIJIE7L1r/0=,tag:lZ0DGxDDzge1dzj/35ZO1w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MXQ1d1o1dWtBdHFYaWhu
            TXY3cWJOY1h2Ulg1M2pQRlEzSzg2ZFpnN1YwClM2VFpFeHNUNnFwZjZCMG15M0Fz
            L3MvQ0l4aEtubytJa2JrWkw3MCs0Y1EKLS0tIHBLUGVia2x3NWU4L2syWFBVNjhH
            eEwvRlZUZlFlUzJSOUpuZWhjczZQRkkKLhZhLVldmWgZ84awLuFaQVX7JbqApZkI
            aQoe1W+kXs3PRbOMiGHm/j6Ves3Jca9MEn4l7JV9jF4iU2GEGMDHgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age132pptnhr58gmqe965wpwxv3p2ud0q95up586fn0wvdh5zljvn48sdq0k6j
    lastmodified: "2026-06-26T03:14:45Z"
    mac: ENC[AES256_GCM,data:kVdMOoyX2R5YxxCdTkZfJTMxkiULnr6Kd4og/ffFHWbXbGVKBwdxlWERjsY/O8ZQ+BLRnLaUD3sAuEKB3KaBxG166F/wRCwfCa+vvTQScTSm0XTB7FFzFDPFCghdc/hZr0/beBhO0VYnEnX5vR+2bc4K6YGAA4xZfn2qDfEDpcc=,iv:aHQGj+KUDDppq0/qmmimrg4kkDoygXR5bXfHhriWzEU=,tag:MwlKtHO7f17+6pHh1bkciw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
